#pragma once

#include <stdio.h>

enum L_HRESULT {
	L_S_OK = 0,
	L_E_FAIL
};

#define CHK_SUCCESS(hr) if(L_E_FAIL == hr) printf("Error found : %s %d\n", __FILE__, __LINE__);

#define CHK_AND_RET_HR(ptr) if(NULL == ptr) {printf("Pointer null : %s %d\n", __FILE__, __LINE__); return L_E_FAIL;}

enum HOUSE {
	UNDEFINED = 0,
	BARATHEON,
	LANNISTER,
	STARK,
	GREYJOY,
	TYRELL,
	MARTELL
};

enum ORDER {
	MARCH_MINUS = 0,
	MARCH,
	MARCH_STAR,
	SUPPORT_1,
	SUPPORT_2,
	SUPPORT_STAR,
	DEFENSE_1,
	DEFENSE_2,
	DEFENSE_STAR,
	CONSOLIDATE_1,
	CONSOLIDATE_2,
	CONSOLIDATE_STAR,
	RAID_1,
	RAID_2,
	RAID_STAR
};

enum UNIT {
	FOOTMAN,
	KNIGHT,
	ENGINE,
	SHIP,
	ARMY
};

enum AREA {
	CASTLE_BLACK = 0,
	BAY_OF_ICE,
	KARHOLD,
	WINTERFELL,
	WINTERFELL_PORT,
	THE_STONY_SHORE,
	WHITE_HARBOR,
	WHITE_HARBOR_PORT,
	THE_SHIVERING_SEA,
	WIDOWS_WATCH,
	THE_NARROW_SEA,
	GREYWATER_WATCH,
	MOAT_CAILIN,
	FUNTS_FINGER,
	SUNSEAT_SEA,
	IRONMANS_BAY,
	IRONMANS_BAY_PORT,
	SEAGARD,
	THE_FINGERS,
	THE_TWINS,
	PYKE,
	THE_MOUNTAINS_OF_THE_MOON,
	RIVERRUN,
	THE_EYRIE,
	LANNISPORT,
	LANNISPORT_PORT,
	HARRENHAL,
	DRAGONSTONE,
	DRAGONSTONE_PORT,
	STONEY_SEPT,
	CRACKLAW_POINT,
	THE_GOLDEN_SEA,
	BLACKWATER_BAY,
	SEAROAD_MARCHES,
	BLACKWATER,
	KNGS_LANDING,
	KINGSWOOD,
	SHIPBREAKER_BAY,
	HIGHGARDEN,
	THE_REACH,
	DORNISH_MARCHES,
	THE_BONEWAY,
	STORMS_END,
	STORMS_END_PORT,
	OLDTOWN,
	OLDTOWN_PORT,
	PRINCES_PASS,
	SEA_OF_DORNE,
	THREE_TOWERS,
	YRONWOOD,
	SUNSPEAR,
	SUNSPEAR_PORT,
	REDWYNE_STRAIGHTS,
	STARFALL,
	SALT_SHORE,
	THE_ARBOR,
	WEST_SUMMER_SEA,
	EAST_SUMMER_SEA
};

enum ELEMENTTYPE {
	UNITTYPE,
	ORDERTYPE,
	POWER,
	GARNISON,
	NEUTRAL,
	WILDLING,
	INFLUENCE
};